[package]
name = "rustler_test"
version = "0.1.0"
authors = ["Various"]

[lib]
name = "rustler_test"
path = "src/lib.rs"
crate_type = ["dylib"]

[dependencies]
rustler = { git = "https://github.com/rusterlium/rustler", branch = "master" }
lazy_static = "1.4"
queues = "1.0.0"
