[package]
name = "native"
version = "0.1.0"
authors = ["Various"]

[lib]
name = "rustler_test"
path = "src/lib.rs"
crate_type = ["dylib"]

[dependencies]
lazy_static = "1.2"
rustler = ">=0.5"
rustler_codegen = ">=0.5"
